import math
import warnings
import numpy as np
from functools import partial
import torch
import torch.nn as nn
import torch.nn.functional as F



def _no_grad_trunc_normal_(tensor, mean, std, a, b):
    def norm_cdf(x):
        # Computes standard normal cumulative distribution function
        return (1. + math.erf(x / math.sqrt(2.))) / 2.

    if (mean < a - 2 * std) or (mean > b + 2 * std):
        warnings.warn("mean is more than 2 std from [a, b] in nn.init.trunc_normal_. "
                      "The distribution of values may be incorrect.",
                      stacklevel=2)

    with torch.no_grad():
        # Values are generated by using a truncated uniform distribution and
        # then using the inverse CDF for the normal distribution.
        # Get upper and lower cdf values
        l = norm_cdf((a - mean) / std)
        u = norm_cdf((b - mean) / std)

        # Uniformly fill tensor with values from [l, u], then translate to
        # [2l-1, 2u-1].
        tensor.uniform_(2 * l - 1, 2 * u - 1)

        # Use inverse cdf transform for normal distribution to get truncated
        # standard normal
        tensor.erfinv_()

        # Transform to proper mean, std
        tensor.mul_(std * math.sqrt(2.))
        tensor.add_(mean)

        # Clamp to ensure it's in the proper range
        tensor.clamp_(min=a, max=b)
        return tensor


def trunc_normal_(tensor, mean=0., std=1., a=-2., b=2.):
    r"""
    Fills the input Tensor with values drawn from a truncated
    normal distribution. The values are effectively drawn from the
    normal distribution :math:`\mathcal{N}(\text{mean}, \text{std}^2)`
    with values outside :math:`[a, b]` redrawn until they are within
    the bounds. The method used for generating the random values works
    best when :math:`a \leq \text{mean} \leq b`.
    Args:
        tensor: an n-dimensional `torch.Tensor`
        mean: the mean of the normal distribution
        std: the standard deviation of the normal distribution
        a: the minimum cutoff value
        b: the maximum cutoff value
    Examples:
        >>> w = torch.empty(3, 5)
        >>> nn.init.trunc_normal_(w)
    """
    return _no_grad_trunc_normal_(tensor, mean, std, a, b)


class GELU(nn.Module):
    def __init__(self):
        super(GELU, self).__init__()

    def forward(self, x):
        return 0.5 * x * (1 + torch.tanh(np.sqrt(2 / np.pi) * (x + 0.044715 * torch.pow(x, 3))))


class _BayesianLayerMixin:
    @staticmethod
    def _resolve_sample_flag(sample=None, mode=None, default=True):
        if mode is not None:
            if sample is not None:
                raise ValueError("Pass either `sample` or `mode`, not both.")
            sample = mode

        if sample is None:
            return bool(default)
        if isinstance(sample, bool):
            return sample
        if sample == "sample":
            return True
        if sample == "mean":
            return False
        raise ValueError(f"Unsupported sampling mode: {sample}")

    @staticmethod
    def _rho_to_sigma(rho):
        return F.softplus(rho)


class BayesLinear(nn.Module, _BayesianLayerMixin):
    def __init__(
        self,
        in_features,
        out_features,
        bias=True,
        posterior_mu_init=0.0,
        posterior_rho_init=-5.0,
    ):
        super().__init__()
        self.in_features = in_features
        self.out_features = out_features
        self.use_bias = bias
        self.posterior_mu_init = float(posterior_mu_init)
        self.posterior_rho_init = float(posterior_rho_init)

        self.weight_mu = nn.Parameter(torch.empty(out_features, in_features))
        self.weight_rho = nn.Parameter(torch.empty(out_features, in_features))

        if self.use_bias:
            self.bias_mu = nn.Parameter(torch.empty(out_features))
            self.bias_rho = nn.Parameter(torch.empty(out_features))
        else:
            self.register_parameter("bias_mu", None)
            self.register_parameter("bias_rho", None)

        self.reset_parameters()

    def reset_parameters(self):
        if self.posterior_mu_init == 0.0:
            nn.init.kaiming_uniform_(self.weight_mu, a=5 ** 0.5)
        else:
            nn.init.normal_(self.weight_mu, mean=self.posterior_mu_init, std=0.1)
        nn.init.constant_(self.weight_rho, self.posterior_rho_init)

        if self.use_bias:
            bound = (1.0 / self.in_features) ** 0.5 if self.in_features > 0 else 0.0
            if self.posterior_mu_init == 0.0:
                nn.init.uniform_(self.bias_mu, -bound, bound)
            else:
                nn.init.normal_(self.bias_mu, mean=self.posterior_mu_init, std=0.1)
            nn.init.constant_(self.bias_rho, self.posterior_rho_init)

    def forward_mean(self, x):
        bias = self.bias_mu if self.use_bias else None
        return F.linear(x, self.weight_mu, bias)

    def forward_sample(self, x):
        weight = self.weight_mu + self._rho_to_sigma(self.weight_rho) * torch.randn_like(self.weight_mu)
        bias = None
        if self.use_bias:
            bias = self.bias_mu + self._rho_to_sigma(self.bias_rho) * torch.randn_like(self.bias_mu)
        return F.linear(x, weight, bias)

    def forward(self, x, sample=None, mode=None):
        sample = self._resolve_sample_flag(sample=sample, mode=mode, default=self.training)
        return self.forward_sample(x) if sample else self.forward_mean(x)


class BayesConv2d(nn.Module, _BayesianLayerMixin):
    def __init__(
        self,
        in_channels,
        out_channels,
        kernel_size,
        stride=1,
        padding=0,
        dilation=1,
        groups=1,
        bias=True,
        posterior_mu_init=0.0,
        posterior_rho_init=-5.0,
    ):
        super().__init__()
        self.in_channels = in_channels
        self.out_channels = out_channels
        self.kernel_size = (kernel_size, kernel_size) if isinstance(kernel_size, int) else kernel_size
        self.stride = (stride, stride) if isinstance(stride, int) else stride
        self.padding = (padding, padding) if isinstance(padding, int) else padding
        self.dilation = (dilation, dilation) if isinstance(dilation, int) else dilation
        self.groups = groups
        self.use_bias = bias
        self.posterior_mu_init = float(posterior_mu_init)
        self.posterior_rho_init = float(posterior_rho_init)

        weight_shape = (out_channels, in_channels // groups, *self.kernel_size)
        self.weight_mu = nn.Parameter(torch.empty(weight_shape))
        self.weight_rho = nn.Parameter(torch.empty(weight_shape))

        if self.use_bias:
            self.bias_mu = nn.Parameter(torch.empty(out_channels))
            self.bias_rho = nn.Parameter(torch.empty(out_channels))
        else:
            self.register_parameter("bias_mu", None)
            self.register_parameter("bias_rho", None)

        self.reset_parameters()

    def reset_parameters(self):
        if self.posterior_mu_init == 0.0:
            nn.init.kaiming_uniform_(self.weight_mu, a=5 ** 0.5)
        else:
            nn.init.normal_(self.weight_mu, mean=self.posterior_mu_init, std=0.1)
        nn.init.constant_(self.weight_rho, self.posterior_rho_init)

        if self.use_bias:
            fan_in, _ = nn.init._calculate_fan_in_and_fan_out(self.weight_mu)
            bound = (1.0 / fan_in) ** 0.5 if fan_in > 0 else 0.0
            if self.posterior_mu_init == 0.0:
                nn.init.uniform_(self.bias_mu, -bound, bound)
            else:
                nn.init.normal_(self.bias_mu, mean=self.posterior_mu_init, std=0.1)
            nn.init.constant_(self.bias_rho, self.posterior_rho_init)

    def forward_mean(self, x):
        bias = self.bias_mu if self.use_bias else None
        return F.conv2d(x, self.weight_mu, bias, self.stride, self.padding, self.dilation, self.groups)

    def forward_sample(self, x):
        weight = self.weight_mu + self._rho_to_sigma(self.weight_rho) * torch.randn_like(self.weight_mu)
        bias = None
        if self.use_bias:
            bias = self.bias_mu + self._rho_to_sigma(self.bias_rho) * torch.randn_like(self.bias_mu)
        return F.conv2d(x, weight, bias, self.stride, self.padding, self.dilation, self.groups)

    def forward(self, x, sample=None, mode=None):
        sample = self._resolve_sample_flag(sample=sample, mode=mode, default=self.training)
        return self.forward_sample(x) if sample else self.forward_mean(x)


class BayesianOverlapPatchEmbed(nn.Module):
    def __init__(self, patch_size=7, stride=4, in_chans=3, embed_dim=768):
        super().__init__()
        patch_size = (patch_size, patch_size)
        self.proj = BayesConv2d(
            in_chans,
            embed_dim,
            kernel_size=patch_size,
            stride=stride,
            padding=(patch_size[0] // 2, patch_size[1] // 2),
        )
        self.norm = nn.LayerNorm(embed_dim)

    def forward(self, x, sample=None):
        x = self.proj(x, sample=sample)
        _, _, H, W = x.shape
        x = x.flatten(2).transpose(1, 2)
        x = self.norm(x)
        return x, H, W


class BayesianAttention(nn.Module):
    def __init__(self, dim, num_heads=8, qkv_bias=False, qk_scale=None, attn_drop=0., proj_drop=0., sr_ratio=1):
        super().__init__()
        assert dim % num_heads == 0, f"dim {dim} should be divided by num_heads {num_heads}."

        self.dim = dim
        self.num_heads = num_heads
        head_dim = dim // num_heads
        self.scale = qk_scale or head_dim ** -0.5

        self.q = BayesLinear(dim, dim, bias=qkv_bias)

        self.sr_ratio = sr_ratio
        if sr_ratio > 1:
            self.sr = BayesConv2d(dim, dim, kernel_size=sr_ratio, stride=sr_ratio)
            self.norm = nn.LayerNorm(dim)
        self.kv = BayesLinear(dim, dim * 2, bias=qkv_bias)

        self.attn_drop = nn.Dropout(attn_drop)
        self.proj = BayesLinear(dim, dim)
        self.proj_drop = nn.Dropout(proj_drop)

    def forward(self, x, H, W, sample=None):
        B, N, C = x.shape
        q = self.q(x, sample=sample).reshape(B, N, self.num_heads, C // self.num_heads).permute(0, 2, 1, 3)

        if self.sr_ratio > 1:
            x_ = x.permute(0, 2, 1).reshape(B, C, H, W)
            x_ = self.sr(x_, sample=sample).reshape(B, C, -1).permute(0, 2, 1)
            x_ = self.norm(x_)
            kv = self.kv(x_, sample=sample).reshape(B, -1, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        else:
            kv = self.kv(x, sample=sample).reshape(B, -1, 2, self.num_heads, C // self.num_heads).permute(2, 0, 3, 1, 4)
        k, v = kv[0], kv[1]

        attn = (q @ k.transpose(-2, -1)) * self.scale
        attn = attn.softmax(dim=-1)
        attn = self.attn_drop(attn)

        x = (attn @ v).transpose(1, 2).reshape(B, N, C)
        x = self.proj(x, sample=sample)
        x = self.proj_drop(x)
        return x


def drop_path(x, drop_prob: float = 0., training: bool = False, scale_by_keep: bool = True):
    """
    Drop paths (Stochastic Depth) per sample (when applied in main path of residual blocks).
    This is the same as the DropConnect impl I created for EfficientNet, etc networks, however,
    the original name is misleading as 'Drop Connect' is a different form of dropout in a separate paper...
    See discussion: https://github.com/tensorflow/tpu/issues/494#issuecomment-532968956 ... I've opted for
    changing the layer and argument names to 'drop path' rather than mix DropConnect as a layer name and use
    'survival rate' as the argument.
    """
    if drop_prob == 0. or not training:
        return x
    keep_prob = 1 - drop_prob
    shape = (x.shape[0],) + (1,) * (x.ndim - 1)  # work with diff dim tensors, not just 2D ConvNets
    random_tensor = x.new_empty(shape).bernoulli_(keep_prob)
    if keep_prob > 0.0 and scale_by_keep:
        random_tensor.div_(keep_prob)
    return x * random_tensor


class DropPath(nn.Module):
    def __init__(self, drop_prob=None, scale_by_keep=True):
        super(DropPath, self).__init__()
        self.drop_prob = drop_prob
        self.scale_by_keep = scale_by_keep

    def forward(self, x):
        return drop_path(x, self.drop_prob, self.training, self.scale_by_keep)


class BayesianDWConv(nn.Module):
    def __init__(self, dim=768):
        super().__init__()
        self.dwconv = BayesConv2d(dim, dim, 3, 1, 1, bias=True, groups=dim)

    def forward(self, x, H, W, sample=None):
        B, N, C = x.shape
        x = x.transpose(1, 2).view(B, C, H, W)
        x = self.dwconv(x, sample=sample)
        x = x.flatten(2).transpose(1, 2)
        return x


class BayesianMlp(nn.Module):
    def __init__(self, in_features, hidden_features=None, out_features=None, act_layer=nn.GELU, drop=0.):
        super().__init__()
        out_features = out_features or in_features
        hidden_features = hidden_features or in_features

        self.fc1 = BayesLinear(in_features, hidden_features)
        self.dwconv = BayesianDWConv(hidden_features)
        self.act = act_layer()
        self.fc2 = BayesLinear(hidden_features, out_features)
        self.drop = nn.Dropout(drop)

    def forward(self, x, H, W, sample=None):
        x = self.fc1(x, sample=sample)
        x = self.dwconv(x, H, W, sample=sample)
        x = self.act(x)
        x = self.drop(x)
        x = self.fc2(x, sample=sample)
        x = self.drop(x)
        return x


class BayesianBlock(nn.Module):
    def __init__(self, dim, num_heads, mlp_ratio=4., qkv_bias=False, qk_scale=None, drop=0., attn_drop=0.,
                 drop_path=0., act_layer=nn.GELU, norm_layer=nn.LayerNorm, sr_ratio=1):
        super().__init__()
        self.norm1 = norm_layer(dim)
        self.attn = BayesianAttention(
            dim, num_heads=num_heads, qkv_bias=qkv_bias, qk_scale=qk_scale,
            attn_drop=attn_drop, proj_drop=drop, sr_ratio=sr_ratio
        )
        self.norm2 = norm_layer(dim)
        self.mlp = BayesianMlp(in_features=dim, hidden_features=int(dim * mlp_ratio), act_layer=act_layer, drop=drop)
        self.drop_path = DropPath(drop_path) if drop_path > 0. else nn.Identity()

    def forward(self, x, H, W, sample=None):
        x = x + self.drop_path(self.attn(self.norm1(x), H, W, sample=sample))
        x = x + self.drop_path(self.mlp(self.norm2(x), H, W, sample=sample))
        return x


class MixVisionTransformer_GSFVI(nn.Module):
    def __init__(self, in_chans=3, num_classes=1000, embed_dims=[32, 64, 160, 256],
                 num_heads=[1, 2, 4, 8], mlp_ratios=[4, 4, 4, 4], qkv_bias=False, qk_scale=None, drop_rate=0.,
                 attn_drop_rate=0., drop_path_rate=0., norm_layer=nn.LayerNorm,
                 depths=[3, 4, 6, 3], sr_ratios=[8, 4, 2, 1]):
        super().__init__()
        self.num_classes = num_classes
        self.depths = depths

        dpr = [x.item() for x in torch.linspace(0, drop_path_rate, sum(depths))]

        self.patch_embed1 = BayesianOverlapPatchEmbed(patch_size=3, stride=2, in_chans=in_chans, embed_dim=embed_dims[0])
        cur = 0
        self.block1 = nn.ModuleList(
            [
                BayesianBlock(
                    dim=embed_dims[0], num_heads=num_heads[0], mlp_ratio=mlp_ratios[0], qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer,
                    sr_ratio=sr_ratios[0]
                )
                for i in range(depths[0])
            ]
        )
        self.norm1 = norm_layer(embed_dims[0])

        self.patch_embed2 = BayesianOverlapPatchEmbed(patch_size=3, stride=2, in_chans=embed_dims[0], embed_dim=embed_dims[1])
        cur += depths[0]
        self.block2 = nn.ModuleList(
            [
                BayesianBlock(
                    dim=embed_dims[1], num_heads=num_heads[1], mlp_ratio=mlp_ratios[1], qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer,
                    sr_ratio=sr_ratios[1]
                )
                for i in range(depths[1])
            ]
        )
        self.norm2 = norm_layer(embed_dims[1])

        self.patch_embed3 = BayesianOverlapPatchEmbed(patch_size=3, stride=2, in_chans=embed_dims[1], embed_dim=embed_dims[2])
        cur += depths[1]
        self.block3 = nn.ModuleList(
            [
                BayesianBlock(
                    dim=embed_dims[2], num_heads=num_heads[2], mlp_ratio=mlp_ratios[2], qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer,
                    sr_ratio=sr_ratios[2]
                )
                for i in range(depths[2])
            ]
        )
        self.norm3 = norm_layer(embed_dims[2])

        self.patch_embed4 = BayesianOverlapPatchEmbed(patch_size=3, stride=2, in_chans=embed_dims[2], embed_dim=embed_dims[3])
        cur += depths[2]
        self.block4 = nn.ModuleList(
            [
                BayesianBlock(
                    dim=embed_dims[3], num_heads=num_heads[3], mlp_ratio=mlp_ratios[3], qkv_bias=qkv_bias,
                    qk_scale=qk_scale,
                    drop=drop_rate, attn_drop=attn_drop_rate, drop_path=dpr[cur + i], norm_layer=norm_layer,
                    sr_ratio=sr_ratios[3]
                )
                for i in range(depths[3])
            ]
        )
        self.norm4 = norm_layer(embed_dims[3])

        self.apply(self._init_weights)

    def _init_weights(self, m):
        if isinstance(m, nn.Linear):
            trunc_normal_(m.weight, std=.02)
            if isinstance(m, nn.Linear) and m.bias is not None:
                nn.init.constant_(m.bias, 0)
        elif isinstance(m, nn.LayerNorm):
            nn.init.constant_(m.bias, 0)
            nn.init.constant_(m.weight, 1.0)
        elif isinstance(m, nn.Conv2d):
            fan_out = m.kernel_size[0] * m.kernel_size[1] * m.out_channels
            fan_out //= m.groups
            m.weight.data.normal_(0, math.sqrt(2.0 / fan_out))
            if m.bias is not None:
                m.bias.data.zero_()

    def forward(self, x,sample=None):
        B = x.shape[0]
        outs = []

        # block1
        x, H, W = self.patch_embed1.forward(x,sample=sample)
        for i, blk in enumerate(self.block1):
            x = blk.forward(x, H, W,sample=sample)
        x = self.norm1(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # block2
        x, H, W = self.patch_embed2.forward(x,sample=sample)
        for i, blk in enumerate(self.block2):
            x = blk.forward(x, H, W,sample=sample)
        x = self.norm2(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # block3
        x, H, W = self.patch_embed3.forward(x,sample=sample)
        for i, blk in enumerate(self.block3):
            x = blk.forward(x, H, W,sample=sample)
        x = self.norm3(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        # block4
        x, H, W = self.patch_embed4.forward(x,sample=sample)
        for i, blk in enumerate(self.block4):
            x = blk.forward(x, H, W,sample=sample)
        x = self.norm4(x)
        x = x.reshape(B, H, W, -1).permute(0, 3, 1, 2).contiguous()
        outs.append(x)

        return outs
